version: '3.6'
services:

  slack_dj_backend:
    env_file:
      - .env
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      dockerfile: ./apps/backend/Dockerfile
      context: ./
      args:
        - LOCAL_USER_ID=${LOCAL_USER_ID}
    volumes:
      - ./apps/backend/src/assets/tracks:/app/apps/backend/src/assets/tracks
    environment:
      - PORT=${BACKEND_PORT}
      - VIRTUAL_HOST=${BACKEND_URL}
      - VIRTUAL_PORT=${BACKEND_PORT}
      - LOCAL_USER_ID=${LOCAL_USER_ID}
      - HOST_IP=${HOST_IP}
    user: ${CURRENT_UID}
    networks:
      backend:
        aliases:
          - backend

  slack_dj_db:
    container_name: ${DB_CONTAINER_NAME}
    image: mariadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    user: ${CURRENT_UID}
    networks:
      backend:
        aliases:
          - database

  slack_dj_icecast:
    container_name: ${ICECAST_CONTAINER_NAME}
    build:
      dockerfile: Dockerfile
      context: ./containers/icecast
    environment:
      - VIRTUAL_HOST=${ICECAST_URL}
      - VIRUTAL_PORT=8000
    user: ${CURRENT_UID}
    networks:
      streaming:
        aliases:
          - icecast

  slack_dj_ices:
    container_name: ${ICES_CONTAINER_NAME}-${ROOM_ID}
    build:
      dockerfile: Dockerfile
      context: ./containers/ices
    volumes:
      - ./dist/apps/backend/assets/tracks:/tracks
    environment:
      - ROOM_ID=${ROOM_ID}
    user: ${CURRENT_UID}
    depends_on:
      - slack_dj_redis
      - slack_dj_icecast
    networks:
      streaming:
        aliases:
          - ices
      backend:
        aliases:
          - ices

  slack_dj_ng:
    container_name: ${NG_CONTAINER_NAME}
    build:
      dockerfile: ./apps/ng/Dockerfile
      context: ./
      args:
      - LOCAL_USER_ID=${LOCAL_USER_ID}
    environment:
    - VIRTUAL_HOST=${NG_URL}
    - VIRTUAL_PORT=80
    - LOCAL_USER_ID=${LOCAL_USER_ID}
    - NG_EXTERNAL_STREAM=${NG_EXTERNAL_STREAM}
    - BACKEND_URL=${BACKEND_URL}
    - RADIO_STREAM_URL=${ICECAST_URL}
    - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
    - SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
    user: ${CURRENT_UID}
    networks:
      frontend:
        aliases:
        - frontend

  slack_dj_nginx_proxy:
    container_name: ${NGINX_PROXY_CONTAINER_NAME}
    build:
      dockerfile: Dockerfile
      context: ./containers/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    user: ${CURRENT_UID}
    networks:
      - streaming
      - frontend
      - backend

  slack_dj_rabbit:
    container_name: slack_dj_rabbit
    hostname: slack_dj_rabbit
    image: rabbitmq:3-management
    user: ${CURRENT_UID}
    networks:
      backend:
        aliases:
          - rabbit
    ports:
    - 15672:15672

  slack_dj_redis:
    container_name: ${REDIS_CONTAINER_NAME}
    volumes:
      - redis:/data
    image: redis:alpine
    user: ${CURRENT_UID}
    networks:
      backend:
        aliases:
          - redis
      streaming:
        aliases:
          - redis

networks:
  streaming:
    driver: 'bridge'

  frontend:
    driver: 'bridge'

  backend:
    driver: 'bridge'

volumes:
  db:
  redis:
