version: '3.6'
services:
  slack_dj_db:
    ports:
    - 3306:3306

  slack_dj_ng:
    build:
      dockerfile: ./apps/sdj/Dockerfile-dev
    environment:
    - VIRTUAL_PORT=4200
    ports:
      - 4200:4200

  slack_dj_backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      dockerfile: ./apps/api/Dockerfile-dev
    ports:
    - 58587:58587
    - 58586:58586
    - 58585:58585
    - 8888:8888
    - 8889:8889
